- name: Install nfs-server
  apt:
    name: nfs-kernel-server
    state: present
  tags:
    - nfs

- name: Allow NFS port
  community.general.ufw:
    state: enabled
    rule: allow
    proto: tcp
    port: 2049
  tags:
    - nfs

- name: Prepare export directory
  file:
    path: "{{ nfs_export_dir }}"
    owner: root
    group: root
    mode: 01777
    state: directory
  tags:
    - nfs

- name: Add NFS export definition
  lineinfile:
    path: /etc/exports
    line: "{{ nfs_export_dir }} {{ nfs_allow_host }}({{ nfs_export_opts }})"
  notify: Export NFS
  tags:
    - nfs
