- name: Update all packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # 1 day
  tags:
    - packages

- name: Install basic tools
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - vim
    - tmux
    - zsh
    - curl
    - wget
  tags:
    - packages

- name: Install yq
  import_tasks: yq.yml
  tags:
    - packages

- name: Set timezone
  timezone:
    name: "{{ timezone }}"
