vagrant_shared_dir: /vagrant
vm_shared_dir: "{{ vagrant_shared_dir }}/shared"


timezone: Asia/Tokyo

# geerlingguy.docker
docker_compose_version: "v2.2.2"
docker_compose_path: /usr/libexec/docker/cli-plugins
docker_daemon_options:
  exec-opts: ["native.cgroupdriver=systemd"]
  log-driver: "json-file"
  log-opts:
    max-size: "100m"
  storage-driver: "overlay2"
docker_users:
  - vagrant

kubernetes_version: 1.21.8
kubernetes_package_version: 1.21.8-00

kubeadm_join_params_json: "{{ vm_shared_dir }}/kubeadm-join-params.json"
control_plane_address: 192.168.56.161
