timezone: Asia/Tokyo

# geerlingguy.docker
docker_compose_version: "v2.2.2"
docker_compose_path: /usr/libexec/docker/cli-plugins
docker_daemon_options:
  exec-opts: ["native.cgroupdriver=systemd"]
  log-driver: "json-file"
  log-opts:
    max-size: "100m"
  storage-driver: "overlay2"
docker_users:
  - vagrant
