- name: Setup firewall for control plane node
  community.general.ufw:
    state: enabled
    rule: allow
    proto: tcp
    port: "{{ item }}"
  with_items:
    - 22           # ssh
    # 6443         Kubernetes API server
    # "2379:2380"  etcd server client API
    # 10250        Kubelet API
    # 10251        kube-scheduler
    # 10252        kube-controller-manager
    - "6443,2379:2380,10250:10252"
  tags:
    - k8s_os_condition
