- name: Setup firewall for worker nodes
  community.general.ufw:
    state: enabled
    rule: allow
    proto: tcp
    port: "{{ item }}"
  with_items:
    - 22           # ssh
    # 10250       Kubelet API
    # 30000:32767 NodePort Service
    - "10250,30000:32767"
  tags:
    - k8s_os_condition
