# https://kubernetes.io/ja/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

- name: Prepare OS conditions for kubeadm
  import_tasks: prepare.yml
  tags:
    - k8s_os_condition

- name: Add Google Cloud Packages apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  tags:
    - kubeadm

- name: Add Kubernetes apt repository
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
  tags:
    - kubeadm

- name: Get node IP address
  shell: ip addr show {{ vm_network_interface }} | grep inet | grep -v inet6 | awk '{print $2}' | cut -f1 -d/
  register: ip_addr
  changed_when: false
  tags:
    - kubeadm

- name: Add kubelet environment file
  lineinfile:
    path: /etc/default/kubelet
    create: yes
    line: KUBELET_EXTRA_ARGS=--node-ip={{ ip_addr.stdout }}
  tags:
    - kubeadm

- name: Install kubelet, kubeadm and kubectl 
  apt:
    name:
      - "kubelet={{ kubernetes_package_version }}"
      - "kubeadm={{ kubernetes_package_version }}"
      - "kubectl={{ kubernetes_package_version }}"
  tags:
    - kubeadm

- name: Hold kubelet, kubeadm and kubectl packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubelet
    - kubeadm
    - kubectl
  tags:
    - kubeadm

- name: Check if kubectl completion file exists
  stat:
    path: /etc/bash_completion.d/kubectl
  register: kubectl_completion
  tags:
    - kubeadm

- name: Create kubectl completion
  shell: "kubectl completion bash >/etc/bash_completion.d/kubectl"
  when: not kubectl_completion.stat.exists
  tags:
    - kubeadm

- name: Set an alias for kubectl
  when: (kubectl_alias is defined) and (kubectl_alias|length > 0)
  blockinfile:
    path: /home/vagrant/.bash_aliases
    block: |
      alias {{ kubectl_alias }}=kubectl
      complete -F __start_kubectl {{ kubectl_alias }}
    create: yes
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: 0644
